### PR TITLE
Clippy suggestions

### PR DESCRIPTION
**Pull request by gulshan**
Clippy suggestions for testing.

### CODE REVIEW

**Comment by mominul** [comment]
I'll merge this after #20 is merged, thanks!

**Comment by mominul** [comment]
@gulshan Can you rebase the PR and run `clippy` again, please? Since the fixed method has new codes from #20

**Comment by gulshan** [comment]
There are some new clippy suggestions on the new "old style kar ordering" code. Should I use them too?

**Comment by mominul** [comment]
@gulshan Yeah, let's try using them too!

**Review by mominul — APPROVED** [review]
Thanks!

**Pull request merged**
